source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'News' do
    pod 'Alamofire', '~> 4.7'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher'
    pod 'HandyJSON', '~> 4.1.1'
    pod 'RxSwift'
end
